### ISSUE TITLE
use managed tags only

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#53]
after 
`
irb(main):018:0> ManageIQ::Consumption::ConsumptionManager.generate_events
`
I am getting error:
```
  Tag Inst Including Associations (0.1ms - 1rows)
  Classification Load (0.2ms)  SELECT  "classifications".* FROM "classifications" WHERE "classifications"."tag_id" = $1 LIMIT $2  [["tag_id", 10000000000187], ["LIMIT", 1]]
  Classification Inst Including Associations (0.0ms - 0rows)
NoMethodError: undefined method `category' for nil:NilClass
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/showback_event.rb:97:in `block in collect_tags'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/showback_event.rb:96:in `collect_tags'
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/consumption_manager.rb:55:in `generate_event_resourc
...
```

because my resource 
```
[20] pry(#<ManageIQ::Consumption::ShowbackEvent>)> resource.tags
=> [#<Tag:0x007faef2cc8c08 id: 10000000000024, name: "/managed/environment/prod">,
 #<Tag:0x007faef2cc8a78 id: 10000000000063, name: "/managed/network_location/dmz">,
 #<Tag:0x007faef2cc8910 id: 10000000000168, name: "/managed/function/app">,
 #<Tag:0x007faef2cc87d0
  id: 10000000000187,
  name: "/miq_policy/assignment/miq_policy_set/10000000000024">]
```
has also different type of tags which can be without category
I believe we need only managed tags here (maybe there is method for it):

```ruby 
--- a/app/models/manageiq/consumption/showback_event.rb
+++ b/app/models/manageiq/consumption/showback_event.rb
@@ -75,6 +75,7 @@ class ManageIQ::Consumption::ShowbackEvent < ApplicationRecord
   def update_event
     generate_data unless self.data.present?
     @metrics = if  resource.methods.include?(:metrics) then metrics_time_range(end_time,start_time.end_of_month) else [] end
     self.data.each do |key,dimensions|
       dimensions.keys.each do |dim|
         self.data[key][dim] = self.send("#{key}_#{dim}", data[key][dim].to_d)
@@ -93,6 +94,7 @@ class ManageIQ::Consumption::ShowbackEvent < ApplicationRecord
       self.context["tag"] = {} unless self.context.has_key?("tag")
     end
     resource.tags.each do |tag|
+      next unless tag.name.ends_with?('managed')
       category = tag.classification.category
       self.context["tag"][category] = [] unless self.context["tag"].has_key?(category)
       self.context["tag"][category] << tag.classification.name unless self.context["tag"]
-
 ```ruby

```

@miq-bot assign @sergio-ocon 
cc @aljesusg

**Comment by lpichler** [comment]
@sergio-ocon I am still getting the error, I had just previously different db.
by command ManageIQ::Consumption::ConsumptionManager.generate_events

**Comment by chargio** [comment]
Hmmmm,

Do you think you can have a look at it @lpichler, or should we wait for @aljesusg ?

**Comment by chargio** [comment]
@aljesusg needs to review tagging to fix this.
