### ISSUE TITLE
error when Service#type is nil for ConsumptionManager.generate_events

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#55]
I am getting error when `Service#type` - not sure it is possible without value in type column - I am just using any provided db.

I run
`
ManageIQ::Consumption::ConsumptionManager.generate_events
`
```
ManageIQ::Consumption::ShowbackUsageType Inst Including Associations (5.4ms - 4rows)
NoMethodError: undefined method `ends_with?' for nil:NilClass
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/showback_event.rb:45:in `block in generate_data'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/showback_event.rb:44:in `generate_data'
	from /Users/liborpichler/manageiq/manageiq-consumption/app/models/manageiq/consumption/consumption_manager.rb:54:in `generate_event_resource'
	from /Users/liborp
```
cc @sergio-ocon @aljesusg

**Comment by chargio** [comment]
@lpichler Can you please have a look at this again?
I've changed the code, as 'services' don't define the type, and it seems that nobody wants to add that code to all classes, so we basically we need to create a workaround. I've added such workaround already for some of my tests.

**Comment by lpichler** [comment]
now it works 👍
